import {
    MdShoppingCart,
    MdLocalGroceryStore,
    MdRestaurant,
    MdLocalCafe,
    MdLocalGasStation,
    MdChildCare,
    MdSchool,
    MdLocalHospital,
    MdLocalPharmacy,
    MdFitnessCenter,
    MdMovie,
    MdLocalMall,
    MdHome,
    MdDirectionsCar,
    MdLocalLaundryService,
    MdLocalAtm,
    MdLocalLibrary,
    MdBeachAccess,
    MdFlight,
    MdHotel,
    MdPets,
    MdSpa,
    MdTheaterComedy,
    MdPark,
    MdLocalBar,
    MdShoppingBag,
    MdLabel,
    MdBookmark,
    MdLocalShipping,
    MdTrain,
    MdDirectionsBike,
    MdTravelExplore,
    MdDirectionsBoat,
    MdDirectionsBus,
    MdSportsSoccer,
    MdSportsBasketball,
    MdSportsVolleyball,
    MdSportsFootball,
    MdSportsTennis,
    MdFastfood,
    MdSportsBar,
    MdWater,
    MdLocalPizza,
    MdEgg,
    MdHealthAndSafety,
    MdPerson,
    MdPeople,
    MdDirectionsWalk,
    MdWoman,
    MdWc,
    MdMan,
    MdFavorite,
    MdHearing,
    MdPublic,
    MdStar,
    MdTv,
    MdAlarm,
    MdDescription,
    MdBattery0Bar,
    MdBattery80,
    MdFireplace,
    MdBook,
    MdGif,
    MdRedeem,
    MdBusiness,
    MdBusinessCenter,
    MdBuild,
    MdCoffee,
    MdPhone,
    MdCalculate,
    MdCall,
    MdCalendarMonth,
    MdCamera,
    MdCreditCard,
    MdChatBubble,
    MdLuggage,
    MdCloud,
    MdDarkMode,
    MdSunny,
    MdPalette,
    MdFormatColorFill,
    MdConstruction,
    MdContentCut,
    MdDrafts,
    MdFingerprint,
    MdSettings,
    MdBolt,
    MdVisibility,
    MdFlag,
    MdFolder,
    MdSportsEsports,
    MdLanguage,
    MdAirplaneTicket,
    MdNotifications,
    MdDelete,
    MdThermostat,
    MdUmbrella,
    MdWaterDrop,
    MdAcUnit,
    MdEmojiEvents,
    MdKey,
    MdBarChart,
    MdImage,
    MdCheckroom,
    MdMonetizationOn,
    MdOutlineMonetizationOn,
    MdSyncAlt,
    MdRestaurantMenu,
    MdFoodBank,
    MdPayments,
    MdSavings,
    MdKeyboard, MdMusicNote, MdWifi, MdSmartphone, MdShield, MdFace3, MdShoppingBasket, MdDirectionsRun, MdLocalParking
} from "react-icons/md";
import {IconType} from "react-icons";
import {IoMdNutrition} from "react-icons/io";

const iconMap: { [icon: string]: IconType } = {
    "parking": MdLocalParking,
    "run": MdDirectionsRun,
    "money": MdOutlineMonetizationOn,
    "hair": MdFace3,
    "shield": MdShield,
    "handy": MdSmartphone,
    "wifi": MdWifi,
    "music": MdMusicNote,
    "fitness-center": MdFitnessCenter,
    "keyboard": MdKeyboard,
    "savings": MdSavings,
    "payments": MdPayments,
    "money-transfer": MdSyncAlt,
    "house": MdHome,
    "shopping-bag": MdShoppingBag,
    "shopping-cart": MdShoppingCart,
    "label": MdLabel,
    "bookmark": MdBookmark,
    "car": MdDirectionsCar,
    "transporter": MdLocalShipping,
    "train": MdTrain,
    "bike": MdDirectionsBike,
    "travel": MdTravelExplore,
    "flight": MdFlight,
    "boat": MdDirectionsBoat,
    "bus": MdDirectionsBus,
    "fuel": MdLocalGasStation,
    "soccer": MdSportsSoccer,
    "basketball": MdSportsBasketball,
    "volleyball": MdSportsVolleyball,
    "football": MdSportsFootball,
    "tennis": MdSportsTennis,
    "beer": MdSportsBar,
    "coffee": MdCoffee,
    "restaurant": MdRestaurant,
    "fast-food": MdFastfood,
    "grocery": IoMdNutrition,
    "wine": MdLocalBar,
    "water": MdWater,
    "pizza": MdLocalPizza,
    "egg": MdEgg,
    "health": MdHealthAndSafety,
    "heart": MdFavorite,
    "person": MdPerson,
    "people": MdPeople,
    "walk": MdDirectionsWalk,
    "wc": MdWc,
    "man": MdMan,
    "women": MdWoman,
    "hear": MdHearing,
    "world": MdPublic,
    "star": MdStar,
    "tv": MdTv,
    "theater": MdTheaterComedy,
    "movie": MdMovie,
    "alarm": MdAlarm,
    "school": MdSchool,
    "note": MdDescription,
    "hospital": MdLocalHospital,
    "battery": MdBattery80,
    "fire": MdFireplace,
    "book": MdBook,
    "gift": MdRedeem,
    "bag": MdBusinessCenter,
    "build": MdBuild,
    "phone": MdPhone,
    "calculator": MdCalculate,
    "call": MdCall,
    "calendar": MdCalendarMonth,
    "camera": MdCamera,
    "card": MdCreditCard,
    "chat": MdChatBubble,
    "suitcase": MdLuggage,
    "cloud": MdCloud,
    "night": MdDarkMode,
    "sunny": MdSunny,
    "pallet": MdPalette,
    "fill": MdFormatColorFill,
    "construct": MdConstruction,
    "scissor": MdContentCut,
    "file": MdDrafts,
    "fingerprint": MdFingerprint,
    "settings": MdSettings,
    "bolt": MdBolt,
    "eye": MdVisibility,
    "flag": MdFlag,
    "folder": MdFolder,
    "video-game": MdSportsEsports,
    "language": MdLanguage,
    "notification": MdNotifications,
    "delete": MdDelete,
    "umbrella": MdUmbrella,
    "water-drop": MdWaterDrop,
    "cold": MdAcUnit,
    "cloth": MdCheckroom,
    "education": MdSchool,
    "pets": MdPets,
    "trophy": MdEmojiEvents,
    "key": MdKey,
    "chart": MdBarChart,
    "image": MdImage,
};

export const getIcon = (icon: string | null) => icon ? iconMap[icon] || MdShoppingBasket : MdShoppingBasket;

export const getIcons = () => Object.keys(iconMap);